wandb_version: 1

data:
  desc: null
  value:
    data_dir: memmap_dataset
    max_seq_len: 2048
    min_seq_len: 1024
    num_workers: 4
model:
  desc: null
  value:
    vocab_size: 1
    input_size: 4
    output_size: 4
    hidden_size: 256
    intermediate_size: 1024
    num_hidden_layers: 9
    num_attention_heads: 8
    num_key_value_heads: 8
    hidden_act: silu
    max_position_embeddings: 2048
    initializer_range: 0.02
    rms_norm_eps: 1.0e-06
    use_cache: true
    pad_token_id: 0
    bos_token_id: 1
    eos_token_id: 2
    pretraining_tp: 1
    tie_word_embeddings: false
    rope_theta: 10000.0
    attention_bias: false
    attention_dropout: 0.0
    mlp_bias: false
validation:
  desc: null
  value:
    interval: -1
    first_n: 10000
    batch_size: 16
    filter_symbols: null
    filter_intervals: 0.0
test:
  desc: null
  value:
    filter_symbols: null
    filter_intervals: 0.0
logging:
  desc: null
  value:
    log_interval: 10
    wandb_enabled: true
    wandb_project: cpt
    wandb_run_name: test_run
    wandb_tags:
    - your_tag1
    - your_tag2
optimizer:
  desc: null
  value:
    batch_size: 32
    total_steps: 10000
    lr: 0.001
    weight_decay: 0.01
    warmup_steps: 100
checkpointing:
  desc: null
  value:
    dir: checkpoints
    interval: 1000
    keep_n_checkpoints: 1
distributed:
  desc: null
  value:
    train_micro_batch_size_per_gpu: 32
    gradient_clipping: 1.0
    fp16:
      enabled: false
    bf16:
      enabled: true
    zero_optimization:
      stage: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.42.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721897695
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 13
      - 16
      - 23
      - 61
      4: 3.10.13
      5: 0.17.5
      6: 4.42.4
      8:
      - 5
      13: linux-x86_64
